name: Bug
title: 'Bug: '
description: bug template
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Fastexcel Version
      placeholder: example 1.2.76
    validations:
      required: true
  - type: input
    id: jdk_version
    attributes:
      label: JDK Version
      placeholder: example OpenJDK 11.0.15
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: example Windows 10 / Ubuntu 20.04
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        Please clearly describe the problem you are facing and attach the error screenshot and error log.
        请清晰的描述你所遇到的问题，并附上错误截图以及错误日志。
    validations:
      required: true