# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        id: lint
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_MD=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }} | grep -E '\.md$' || true)
          else
            CHANGED_MD=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -E '\.md$' || true)
          fi
          if [ -n "$CHANGED_MD" ]; then
            markdownlint-cli2 "$CHANGED_MD" --config website/.markdownlint-cli2.jsonc > lint-result.txt || true
            if [ -s lint-result.txt ]; then
              echo "Lint failed."
              # Output non-compliant file contents to comment-body.txt
              for file in $CHANGED_MD; do
                echo "\n---\n**$file Content:**\n" >> comment-body.txt
                echo '\n```markdown' >> comment-body.txt
                cat "$file" >> comment-body.txt
                echo '\n```' >> comment-body.txt
              done
              echo "\n---\n**Lint Results:**\n" >> comment-body.txt
              cat lint-result.txt >> comment-body.txt
              exit 1
            fi
          else
            echo "No markdown files changed, skipping lint."
          fi
